# Generated by Django 4.2.29 on 2026-04-04 08:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRegistry',
            fields=[
                ('asset_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_gedung', models.CharField(max_length=255)),
                ('lokasi_gps', models.CharField(help_text='Lat, Lng string', max_length=100)),
                ('lpl_grade', models.CharField(choices=[('I', 'LPL I'), ('II', 'LPL II'), ('III', 'LPL III'), ('IV', 'LPL IV')], max_length=4)),
                ('kapasitas_desain_ka', models.IntegerField(editable=False, help_text='Auto-filled from LPL grade')),
                ('tahun_instalasi', models.IntegerField()),
                ('skor_kesehatan_aset', models.FloatField(default=1.0, help_text='0.0 (dead) to 1.0 (pristine)')),
                ('jenis_material_konduktor', models.CharField(blank=True, default='', max_length=50)),
                ('resistivitas_tanah', models.FloatField(blank=True, help_text='Soil resistivity in Ω·m', null=True)),
                ('catatan', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'asset_registry',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Manajer', 'Manajer'), ('Teknisi', 'Teknisi')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='LightningEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('estimasi_arus_puncak_ka', models.FloatField(help_text='Ipeak in kA')),
                ('rasio_stres', models.FloatField(default=0.0, editable=False, help_text='Auto: Ipeak / kapasitas_desain_ka')),
                ('source_type', models.CharField(choices=[('Manual', 'Manual'), ('AudioEstimation', 'Audio Estimation'), ('Sensor', 'Sensor')], default='Manual', max_length=20)),
                ('fuzzy_output_score', models.FloatField(blank=True, help_text='IUI 0-100', null=True)),
                ('fuzzy_output_label', models.CharField(blank=True, default='', max_length=30)),
                ('catatan', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.assetregistry')),
            ],
            options={
                'db_table': 'lightning_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InspectionLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tgl_inspeksi', models.DateTimeField()),
                ('status_air_terminal', models.CharField(choices=[('OK', 'OK'), ('Rusak', 'Rusak'), ('Meleleh', 'Meleleh'), ('Terkorosi', 'Terkorosi')], max_length=20)),
                ('status_down_conductor', models.CharField(choices=[('OK', 'OK'), ('Klem_Lepas', 'Klem Lepas'), ('Bengkok', 'Bengkok'), ('Putus', 'Putus')], max_length=20)),
                ('status_grounding', models.CharField(choices=[('OK', 'OK'), ('High_Resistance', 'High Resistance'), ('Terkorosi', 'Terkorosi')], max_length=20)),
                ('resistansi_grounding_ohm', models.FloatField(blank=True, null=True)),
                ('status_spd', models.CharField(blank=True, choices=[('OK', 'OK'), ('Degraded', 'Degraded'), ('Failed', 'Failed')], default='', max_length=20)),
                ('arus_bocor_spd_ma', models.FloatField(blank=True, null=True)),
                ('status_bonding', models.CharField(blank=True, choices=[('OK', 'OK'), ('Longgar', 'Longgar'), ('Terputus', 'Terputus')], default='', max_length=20)),
                ('status_kabel_instalasi', models.CharField(blank=True, choices=[('OK', 'OK'), ('Terkelupas', 'Terkelupas'), ('Terbakar', 'Terbakar')], default='', max_length=20)),
                ('catatan_teknisi', models.TextField(blank=True, default='')),
                ('foto_bukti_url', models.TextField(blank=True, default='', help_text='Comma-separated photo paths')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='core.assetregistry')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='core.lightningevent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='core.user')),
            ],
            options={
                'db_table': 'inspection_logs',
                'ordering': ['-tgl_inspeksi'],
            },
        ),
    ]
