# Generated by Django 4.2.29 on 2026-05-06 01:54

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Manajer', 'Manajer'), ('Teknisi', 'Teknisi')], default='Teknisi', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AssetRegistry',
            fields=[
                ('asset_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_gedung', models.CharField(max_length=255)),
                ('lokasi_gps', models.CharField(help_text='Lat, Lng string', max_length=100)),
                ('lpl_grade', models.CharField(choices=[('I', 'LPL I'), ('II', 'LPL II'), ('III', 'LPL III'), ('IV', 'LPL IV')], max_length=4)),
                ('kapasitas_desain_ka', models.IntegerField(editable=False, help_text='Auto-filled from LPL grade')),
                ('tahun_instalasi', models.IntegerField()),
                ('skor_kesehatan_aset', models.FloatField(default=1.0, help_text='0.0 (dead) to 1.0 (pristine)')),
                ('jenis_material_konduktor', models.CharField(blank=True, default='', max_length=50)),
                ('resistivitas_tanah', models.FloatField(blank=True, help_text='Soil resistivity in Ω·m', null=True)),
                ('catatan', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'asset_registry',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('alamat', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='LightningEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('estimasi_arus_puncak_ka', models.FloatField(help_text='Ipeak in kA')),
                ('rasio_stres', models.FloatField(default=0.0, editable=False, help_text='Auto: Ipeak / kapasitas_desain_ka')),
                ('fuzzy_output_score', models.FloatField(blank=True, help_text='IUI 0-100', null=True)),
                ('fuzzy_output_label', models.CharField(blank=True, default='', max_length=30)),
                ('catatan', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.assetregistry')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lightning_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InspectionLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tgl_inspeksi', models.DateTimeField()),
                ('status_air_terminal', models.CharField(choices=[('OK', 'OK'), ('Rusak', 'Rusak'), ('Meleleh', 'Meleleh'), ('Terkorosi', 'Terkorosi')], max_length=20)),
                ('status_down_conductor', models.CharField(choices=[('OK', 'OK'), ('Klem_Lepas', 'Klem Lepas'), ('Bengkok', 'Bengkok'), ('Putus', 'Putus')], max_length=20)),
                ('status_grounding', models.CharField(choices=[('OK', 'OK'), ('High_Resistance', 'High Resistance'), ('Terkorosi', 'Terkorosi')], max_length=20)),
                ('resistansi_grounding_ohm', models.FloatField(blank=True, null=True)),
                ('status_spd', models.CharField(blank=True, choices=[('OK', 'OK'), ('Degraded', 'Degraded'), ('Failed', 'Failed')], default='', max_length=20)),
                ('arus_bocor_spd_ma', models.FloatField(blank=True, null=True)),
                ('status_bonding', models.CharField(blank=True, choices=[('OK', 'OK'), ('Longgar', 'Longgar'), ('Terputus', 'Terputus')], default='', max_length=20)),
                ('status_kabel_instalasi', models.CharField(blank=True, choices=[('OK', 'OK'), ('Terkelupas', 'Terkelupas'), ('Terbakar', 'Terbakar')], default='', max_length=20)),
                ('catatan_teknisi', models.TextField(blank=True, default='')),
                ('foto_bukti_url', models.TextField(blank=True, default='', help_text='Comma-separated photo paths')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amends', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='core.inspectionlog')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='core.assetregistry')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='core.lightningevent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inspection_logs',
                'ordering': ['-tgl_inspeksi'],
            },
        ),
        migrations.AddField(
            model_name='assetregistry',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='core.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
