# Generated by Django 4.2.29 on 2026-05-06 02:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionlog',
            name='foto_bukti_url',
        ),
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('photo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='inspections/%Y/%m/')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.inspectionlog')),
            ],
            options={
                'db_table': 'inspection_photos',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
