# Generated by Django 4.2.29 on 2026-05-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_inspectionlog_foto_bukti_url_inspectionphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
    ]
