# Generated by Django 4.2.29 on 2026-05-18 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_inspectionlog_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetregistry',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='assetregistry',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inspectionlog',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='core.assetregistry'),
        ),
        migrations.AlterField(
            model_name='lightningevent',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.assetregistry'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Edited'), ('amend', 'Amended'), ('delete', 'Soft-deleted'), ('restore', 'Restored'), ('lightning', 'Lightning recorded'), ('stale_asset', 'Asset overdue for inspection'), ('verify', 'Verified'), ('request_revision', 'Revision Requested'), ('asset_create', 'Asset Created'), ('asset_update', 'Asset Edited'), ('asset_delete', 'Asset Soft-deleted'), ('asset_restore', 'Asset Restored')], max_length=20),
        ),
        migrations.CreateModel(
            name='AssetAudit',
            fields=[
                ('audit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Edited'), ('delete', 'Soft-deleted'), ('restore', 'Restored'), ('purge', 'Hard-deleted')], max_length=20)),
                ('diff', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='core.assetregistry')),
            ],
            options={
                'db_table': 'asset_audits',
                'ordering': ['-created_at'],
            },
        ),
    ]
