# Generated by Django 4.2.29 on 2026-05-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_assetregistry_deleted_at_assetregistry_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionlogaudit',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Edited'), ('amend', 'Amended'), ('amended_by', 'Amended By'), ('photo_added', 'Photo Added'), ('delete', 'Soft-deleted'), ('restore', 'Restored'), ('purge', 'Hard-deleted'), ('verify', 'Verified'), ('request_revision', 'Revision Requested'), ('revoke_verification', 'Verification Revoked')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Edited'), ('amend', 'Amended'), ('delete', 'Soft-deleted'), ('restore', 'Restored'), ('lightning', 'Lightning recorded'), ('stale_asset', 'Asset overdue for inspection'), ('verify', 'Verified'), ('request_revision', 'Revision Requested'), ('revoke_verification', 'Verification Revoked'), ('asset_create', 'Asset Created'), ('asset_update', 'Asset Edited'), ('asset_delete', 'Asset Soft-deleted'), ('asset_restore', 'Asset Restored')], max_length=20),
        ),
    ]
