# Generated by Django 4.2.29 on 2026-05-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_per_component_assets'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assetcomponent',
            name='one_active_component_per_type_per_asset',
        ),
        migrations.AddField(
            model_name='inspectionlog',
            name='health_after',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='assetcomponent',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('end_date__isnull', True)), fields=('asset', 'component_type'), name='one_active_component_per_type_per_asset'),
        ),
    ]
