# Generated by Django 4.2.29 on 2026-05-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_health_after_field'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inspectionlog',
            constraint=models.UniqueConstraint(condition=models.Q(('amends__isnull', False)), fields=('amends',), name='inspection_log_one_amendment_per_original'),
        ),
    ]
