# Generated by Django 4.2.29 on 2026-06-11 03:37

from django.db import migrations, models


def fix_legacy_replace_actions(apps, schema_editor):
    """Repair audit rows written with the old, invalid action codes."""
    AssetAudit = apps.get_model('core', 'AssetAudit')
    AssetAudit.objects.filter(action='replaced').update(action='replace_out')
    AssetAudit.objects.filter(action='replaces').update(action='replace_in')


def reverse_fix(apps, schema_editor):
    AssetAudit = apps.get_model('core', 'AssetAudit')
    AssetAudit.objects.filter(action='replace_out').update(action='replaced')
    AssetAudit.objects.filter(action='replace_in').update(action='replaces')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_health_recomputed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetaudit',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Edited'), ('delete', 'Soft-deleted'), ('restore', 'Restored'), ('purge', 'Hard-deleted'), ('replace_out', 'Replaced (superseded by new asset)'), ('replace_in', 'Replaces (supersedes old asset)')], max_length=20),
        ),
        migrations.RunPython(fix_legacy_replace_actions, reverse_fix),
    ]
