# Generated by Django 4.2.29 on 2026-06-11 14:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


def backfill_tanggal_instalasi(apps, schema_editor):
    """Existing year-only assets: set tanggal_instalasi to Jan 1 of the install year,
    preserving the historical age behaviour for components already on record."""
    AssetRegistry = apps.get_model('core', 'AssetRegistry')
    for asset in AssetRegistry.objects.filter(tanggal_instalasi__isnull=True):
        if asset.tahun_instalasi:
            AssetRegistry.objects.filter(pk=asset.pk).update(
                tanggal_instalasi=datetime.date(asset.tahun_instalasi, 1, 1)
            )


def reverse_backfill(apps, schema_editor):
    AssetRegistry = apps.get_model('core', 'AssetRegistry')
    AssetRegistry.objects.update(tanggal_instalasi=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_assetaudit_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcomponent',
            name='last_eol_notified_at',
            field=models.DateTimeField(blank=True, help_text='When the last EOL notification fired (cooldown anchor)', null=True),
        ),
        migrations.AddField(
            model_name='assetcomponent',
            name='last_eol_tier',
            field=models.CharField(blank=True, default='', help_text="Last EOL tier notified: '' | 'warning' | 'urgent'", max_length=10),
        ),
        migrations.AddField(
            model_name='assetregistry',
            name='tanggal_instalasi',
            field=models.DateField(blank=True, help_text='Tanggal instalasi presisi; tahun_instalasi diturunkan dari sini. Dipakai untuk menanggali komponen saat aset dibuat/diganti.', null=True),
        ),
        migrations.RunPython(backfill_tanggal_instalasi, reverse_backfill),
        migrations.AddField(
            model_name='notification',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.assetcomponent'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Edited'), ('amend', 'Amended'), ('delete', 'Soft-deleted'), ('restore', 'Restored'), ('lightning', 'Lightning recorded'), ('stale_asset', 'Asset overdue for inspection'), ('verify', 'Verified'), ('request_revision', 'Revision Requested'), ('revoke_verification', 'Verification Revoked'), ('asset_create', 'Asset Created'), ('asset_update', 'Asset Edited'), ('asset_delete', 'Asset Soft-deleted'), ('asset_restore', 'Asset Restored'), ('component_eol_warning', 'Komponen mendekati masa pakai'), ('component_eol_urgent', 'Komponen hampir habis masa pakai')], max_length=30),
        ),
    ]
