# Generated by Django 4.2.29 on 2026-06-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_assetcomponent_last_eol_notified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Edited'), ('amend', 'Amended'), ('delete', 'Soft-deleted'), ('restore', 'Restored'), ('lightning', 'Lightning recorded'), ('stale_asset', 'Asset overdue for inspection'), ('verify', 'Verified'), ('request_revision', 'Revision Requested'), ('revoke_verification', 'Verification Revoked'), ('asset_create', 'Asset Created'), ('asset_update', 'Asset Edited'), ('asset_delete', 'Asset Soft-deleted'), ('asset_restore', 'Asset Restored'), ('component_eol_warning', 'Komponen mendekati masa pakai'), ('component_eol_urgent', 'Komponen hampir habis masa pakai'), ('component_hard_fail', 'Komponen gagal kritis')], max_length=30),
        ),
    ]
