# Generated by Django 4.2.29 on 2026-06-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_notification_verb'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assetregistry',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'nama_gedung'), name='uniq_live_asset_name_per_org'),
        ),
    ]
