# Generated by Django 4.2.29 on 2026-07-04 14:26

from django.db import migrations, models


def backfill_kategori_magnitudo(apps, schema_editor):
    """Populate kategori_magnitudo for existing events from their peak current."""
    from fuzzy_engine import fuzzy_config as cfg
    LightningEvent = apps.get_model('core', 'LightningEvent')
    for ev in LightningEvent.objects.all().iterator():
        band = cfg.classify_magnitude_ka(ev.estimasi_arus_puncak_ka)
        if band and ev.kategori_magnitudo != band:
            LightningEvent.objects.filter(pk=ev.pk).update(kategori_magnitudo=band)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_extend_component_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightningevent',
            name='kategori_magnitudo',
            field=models.CharField(blank=True, default='', editable=False, help_text='Auto absolute-kA band: kecil | sedang_kecil | sedang | besar', max_length=15),
        ),
        migrations.RunPython(backfill_kategori_magnitudo, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='inspectionlog',
            name='status_down_conductor',
            field=models.CharField(choices=[('OK', 'OK'), ('Klem_Lepas', 'Klem Lepas'), ('Bengkok', 'Bengkok'), ('Putus', 'Putus'), ('TK_Rusak', 'Termination Kit Rusak')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inspectionlog',
            name='status_spd',
            field=models.CharField(choices=[('OK', 'OK'), ('Degraded', 'Degraded'), ('Failed', 'Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Edited'), ('amend', 'Amended'), ('delete', 'Soft-deleted'), ('restore', 'Restored'), ('lightning', 'Lightning recorded'), ('stale_asset', 'Asset overdue for inspection'), ('verify', 'Verified'), ('request_revision', 'Revision Requested'), ('revoke_verification', 'Verification Revoked'), ('asset_create', 'Asset Created'), ('asset_update', 'Asset Edited'), ('asset_delete', 'Asset Soft-deleted'), ('asset_restore', 'Asset Restored'), ('component_eol_warning', 'Komponen mendekati masa pakai'), ('component_eol_urgent', 'Komponen hampir habis masa pakai'), ('component_hard_fail', 'Komponen gagal kritis'), ('incidental_inspection', 'Inspeksi insidental (sambaran besar)'), ('periodic_inspection_due', 'Inspeksi periodik jatuh tempo')], max_length=30),
        ),
    ]
