# Generated by Django 4.2.29 on 2026-07-05 20:58

from django.db import migrations, models
import django.db.models.deletion


def backfill_predecessor(apps, schema_editor):
    """Link already-replaced assets from the existing audit trail: each 'replace_in'
    audit carries the old asset id in diff['old_asset_id']. Only fills nulls."""
    AssetRegistry = apps.get_model('core', 'AssetRegistry')
    AssetAudit = apps.get_model('core', 'AssetAudit')
    for audit in AssetAudit.objects.filter(action='replace_in'):
        old_id = (audit.diff or {}).get('old_asset_id')
        if not old_id or audit.asset_id is None:
            continue
        if AssetRegistry.objects.filter(pk=old_id).exists():
            AssetRegistry.objects.filter(
                pk=audit.asset_id, predecessor__isnull=True
            ).update(predecessor_id=old_id)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_lightningevent_kategori_magnitudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetregistry',
            name='predecessor',
            field=models.ForeignKey(blank=True, help_text='The asset this one replaced; used to inherit strike/inspection history.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='core.assetregistry'),
        ),
        migrations.RunPython(backfill_predecessor, migrations.RunPython.noop),
    ]
